package/elfutils: fix build on microblaze
Fix the following build failure on microblaze:

dwelf_elf_begin.c:62:1: error: symver is only supported on ELF platforms
   62 | OLD_VERSION (dwelf_elf_begin, ELFUTILS_0.175)
      | ^~~~~~~~~~~
dwelf_elf_begin.c:62:1: error: symver is only supported on ELF platforms

Fixes:
 - http://autobuild.buildroot.org/results/5ca2aa5c76415690ad4a85837ba47e7bcfbdbcbc

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 8ef2bb44379e4763682199ad2ecfd23d51cbacc0)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>